#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "slant"
    statusline_iseparator = "arrow" # bar
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    relativenumber = false
    autocomplete_method = 'coc'
    autocomplete_parens = false
    statusline_unicode_symbols = true
    default_indent = 2
    expand_tab = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    # vimcompatible = true
    bootstrap_before = "myspacevim#before"
    filemanager = "nerdtree"
    filetree_direction = 'left'

[[custom_plugins]]
  name = 'evanleck/vim-svelte'

[[custom_plugins]]
  name = 'vim-crystal/vim-crystal'

[[custom_plugins]]
  name = 'neoclide/coc.nvim'


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart" # cycle

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 10


[[layers]]
name = "lang#javascript"

[[layers]]
name = "git"
#  git-plugin = "fugitive"


[[layers]]
name = "acpi"
